services:
  desafio_codecon_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'desafio_codecon_dev'
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npm start"
networks:
  default:
    name: local
