export const mockUsers = [
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `br-${i}`,
    nome: `User BR ${i}`,
    idade: 25 + i,
    score: 1000 + i,
    ativo: true,
    pais: 'Brasil',
    equipe: JSON.stringify({ nome: 'Equipe BR', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-20', action: 'login' }]),
  })),
  ...Array.from({ length: 6 }, (_, i) => ({
    id: `ar-${i}`,
    nome: `User AR ${i}`,
    idade: 30 + i,
    score: 950 + i,
    ativo: true,
    pais: 'Argentina',
    equipe: JSON.stringify({ nome: 'Equipe AR', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-21', action: 'logout' }]),
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `cl-${i}`,
    nome: `User CL ${i}`,
    idade: 22 + i,
    score: 970 + i,
    ativo: true,
    pais: 'Chile',
    equipe: JSON.stringify({ nome: 'Equipe CL', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-22', action: 'login' }]),
  })),
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `mx-${i}`,
    nome: `User MX ${i}`,
    idade: 28 + i,
    score: 880 + i,
    ativo: true,
    pais: 'México',
    equipe: JSON.stringify({ nome: 'Equipe MX', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-23', action: 'logout' }]),
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `pe-${i}`,
    nome: `User PE ${i}`,
    idade: 32 + i,
    score: 910 + i,
    ativo: true,
    pais: 'Peru',
    equipe: JSON.stringify({ nome: 'Equipe PE', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-24', action: 'login' }]),
  })),
  ...Array.from({ length: 2 }, (_, i) => ({
    id: `co-${i}`,
    nome: `User CO ${i}`,
    idade: 27 + i,
    score: 890 + i,
    ativo: true,
    pais: 'Colômbia',
    equipe: JSON.stringify({ nome: 'Equipe CO', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-25', action: 'logout' }]),
  })),
  {
    id: 'uy-0',
    nome: 'User UY 0',
    idade: 35,
    score: 900,
    ativo: true,
    pais: 'Uruguai',
    equipe: JSON.stringify({ nome: 'Equipe UY', lider: false, projetos: [] }),
    logs: JSON.stringify([{ date: '2025-04-25', action: 'login' }]),
  },
]
